### PR TITLE
Add French Translations

### PR DESCRIPTION
**Pull request by ZandercraftGames**
This adds accurate French translations to WildBeast.
Hope that this helps @Dougley @linuswillner... 
I'm from Canada and I speak French almost fluently.

### CODE REVIEW

**Comment by caf203** [comment]
Thank you for showing interest in contributing to our translations! Please compare your changes to [what we have in i18n](https://i18n.thesharks.xyz/project/wildbeast) as that is our official language program.

**Comment by ZandercraftGames** [comment]
@caf203 it seems there is a glitch
image

**Comment by ZandercraftGames** [comment]
Any character with a ` above it... like é or à shows as a � in Discord.... but they can be sent by a normal user.

**Comment by ZandercraftGames** [comment]
I also cannot edit your translated work... it requires an account.

**Comment by caf203** [comment]
Yes, you must create an account and be accepted into the program to contribute to a language. It helps to cut down on memey/garbage translations. As for your image, I'm afraid I'm unsure how you got that result?
image

**Comment by ZandercraftGames** [comment]
try running it with my translations file.

**Comment by ZandercraftGames** [comment]
Also... you can see the file here in the pull request.

**Comment by ZandercraftGames** [comment]
P.S. I applied to join the translation team.

**Comment by caf203** [comment]
I don't need to manually edit my language file to get your contributions. That's the beauty of i18n. Please make an account and suggest your changes there. We know that language strings pulled from i18n and managed by the bot aren't giving the weird symbols you're getting. Furthermore, [take a look here](https://raw.githubusercontent.com/TheSharks/WildBeast/926cbc1e6e03be010410f0453461c85bf4a3f9d7/src/languages/fr-FR.json). This is the raw json file of your commit, you can see how the encoding is messed up.

**Comment by Nenkai** [comment]
I am already in charge of french translations. Most of them are already translated, so there is not a current need for additional help.

**Comment by ZandercraftGames** [comment]
Oh... Well. I discovered why... It wasnt in UTF-8 encoding. I updated it.

**Comment by linuswillner** [comment]
Translation files are not distributed with the source code, they are downloaded from Crowdin separately for use. Additionally, after investigation, @Nenkai tells me that these changes are marginal and in some cases even worse than the current ones.

Based on this I’m closing this PR. If you wish to contribute to the French translations, the Crowdin page for our project is the way to go.

**Pull request closed without merging**
