### PR TITLE
Voice

### PR DESCRIPTION
**Pull request by Dougley**
Merge voice branch into exp, we can develop against exp from now 

Honestly I kinda just want to get rid of the branch

### CODE REVIEW

**Comment by zaza7** [comment]
I make no promises that future commits will not break the build.

**Comment by Dougley** [comment]
Didn't expect anything less

**Comment by caf203** [comment]
I still see a to-do in src/commands/request.js

**Comment by zaza7** [comment]
Exactly so while you have fun with exp, I can push to voice branch at any time without breaking things.

**Comment by Dougley** [comment]
Merging into experimental since not only voice development happened on this branch.

**Pull request merged**
