### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by zaza7**
github says i can't merge, i say otherwise. watch me ( ͡° ͜ʖ ͡°)

### CODE REVIEW

**Comment by SteamingMutt** [comment]
Blocked by #221

**Comment by SteamingMutt** [comment]
We're still waiting on the docs from @LWTechGaming, otherwise I see no problems 👌

**Comment by LWTechGaming** [comment]
It's almost ready 👌

**Comment by LWTechGaming** [comment]
Documentation release candidate PR has been published. @SteamingMutt, @zaza7, @thenightex and @Nenkai have been requested to submit their quality control review for https://github.com/TheSharks/WildBeastDocs/pull/17. When the approval is given from the rest on the docs, I will approve these changes 👌

**Comment by LWTechGaming** [comment]
Documentation is up to date and ready to go live. Just the changelog now, I'll leave that to @SteamingMutt

**Pull request merged**
